build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
  armhf: ghcr.io/home-assistant/armhf-base:3.19
  armv7: ghcr.io/home-assistant/armv7-base:3.19
  i386: ghcr.io/home-assistant/i386-base:3.19
labels:
  org.opencontainers.image.title: "SMS Gammu Gateway"
  org.opencontainers.image.description: "REST API SMS Gateway using python-gammu for USB GSM modems"
  org.opencontainers.image.source: "https://github.com/PavelVe/home-assistant-addons"
  org.opencontainers.image.authors: "PavelVe"
  org.opencontainers.image.licenses: "Apache-2.0"
args:
  TEMPIO_VERSION: "2021.09.0"